### ISSUE TITLE
S.Bool.flip observes an invisible change

### ISSUE THREAD

**Issue by art-w** [dbuenzli/react#17]
The documentation states that `S.Bool.flip true cx` can be `false` initially if `cx` triggers at time 0 (this is perfectly reasonnable.) In the following, the fact that `cx` triggers at time 0 seems to only be observable by `S.Bool.flip` (this is less reasonnable.)

``` ocaml
let x, set_x = S.create 0

let counter = ref 0

let err = S.bind x (fun v ->

    incr counter ;
    let id = !counter in
    Printf.printf "Update step %i\n%!" id ;

    let cx = S.changes x in (* new dynamic signal, so x hasn't change yet *)
    let test_flip = S.Bool.flip true cx in (* should be true initially *)

    let s =
      S.l2 (fun b w ->
             Printf.printf "[%i] b = %s, w = %i\n%!" (* b = false, w = 42 *)
                id (if b then "true" else "false") w)
        test_flip
        (S.hold 42 cx) in

    let e = (* never prints *)
      E.l1 (fun w -> Printf.printf "[%i] event w = %i\n%!" id w) cx in

    ignore (S.retain s (fun _ -> ignore e)) ;

    s)

let () =
  List.iter
    (fun v -> Gc.full_major () ; Printf.printf "---\n%!" ; set_x v)
    [1;2]
```

Outputs (*) :

```
Update step 1
[1] b = true, w = 42

---
Update step 2
[2] b = false, w = 42

---
Update step 3
[3] b = false, w = 42
```

So neither `S.hold` nor `E.map` sees the event at time 0. The exceptional behaviour of [flip is tested](https://github.com/dbuenzli/react/blob/master/test/test.ml#L1236), so maybe I'm missing something?

---

(*) There is a small leak of previous signals/events, so the real output is:

```
Update step 1
[1] b = true, w = 42

---
Update step 2
[1] event w = 1
[1] b = false, w = 1
[2] b = false, w = 42

---
Update step 3
[2] event w = 2
[2] b = true, w = 2
[3] b = false, w = 42
```

**Comment by dbuenzli** [comment]
> The exceptional behaviour of flip is tested, so maybe I'm missing something?

This is not exceptional behaviour, it is corresponds to the semantics. It's rather the fact that the dynamic `e` and `s` do not get updated in step 2 and 3 (in which `cx` does occur) that is strange.

**Comment by dbuenzli** [comment]
Well in fact [here](http://erratique.ch/software/react/doc/React.html#sem) is written: 

    It is important to note that in these semantic descriptions the origin of time t = 0 is 
    always fixed at the time at which the combinator creates the event or the signal and the
    semantics of the dependents is evaluated relative to this timeline.

So in fact the `cx` never occur in the step they are created since as far as the  `S.changes` combinator is concerned (and implemented) the time `0-dt` at which to evaluate `x` does not exist. It thus effectively seems that the `test_flip`s should also not see an occurence here and that the test you mention is wrong.

**Comment by dbuenzli** [comment]
I found the problem. In fact when we are in a dynamic creation [we schedule the node](https://github.com/dbuenzli/react/blob/349ea863373c748702c4448d26a6f18aa379a8be/src/react.ml#L1429-L1432) so its [update function](https://github.com/dbuenzli/react/blob/349ea863373c748702c4448d26a6f18aa379a8be/src/react.ml#L1424) will be called. 

However this function unconditionally flips when called. This is right for subsequent updates since the update function will get scheduled iff the event occurs. But this is not right for dynamics since we don't know if the event will occur yet.
